[versions]
kotlinVersion = "1.7.10"
dokkaVersion = "1.7.10"
appcompatVersion = "1.3.0"
espressoVersion = "3.5.0"
junitVersion = "4.13.2"
junitExtVersion = "1.1.3"
multidexVersion = "2.0.1"
materialVersion = "1.4.0"
activityComposeVersion = "1.5.1"
composeVersion = "1.3.1"
composeCompilerVersion = "1.3.2"

[libraries]
composeActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeVersion" }
composeMaterial = { module = "androidx.compose.material:material", version.ref = "composeVersion" }
composeJunit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeVersion" }
composeTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeVersion" }
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
dokka = { module = "org.jetbrains.dokka:kotlin-as-java-plugin", version.ref = "dokkaVersion" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
junitExt = { module = "androidx.test.ext:junit", version.ref = "junitExtVersion" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidexVersion" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }

[plugins]
dokkaPlugin = { id = "org.jetbrains.dokka" }